name: MainDeployCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      env:
        PERSONAL_EMAIL: ${{ secrets.PERSONAL_EMAIL }}
        PERSONAL_USERNAME: ${{ secrets.PERSONAL_USERNAME }}
        PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
      run: |
        git config --global user.email "$PERSONAL_EMAIL"
        git config --global user.name "$PERSONAL_USERNAME"
        git remote set-url origin https://$PERSONAL_ACCESS_TOKEN_GITHUB@github.com/mutabbir786/quizz-app.git
        npm run deploy
